const IntergerStartingAtZero = {
  type: Number,
  get: (v) => Math.round(v),
  set: (v) => Math.round(v),
  min: 0,
  default: 0,
};

module.exports = {
  name: 'character',
  inherit: [require('./entity.model')],
  schema: {
    user: {
      type: String,
      index: true,
      unique: true,
      required: true,
    },
    level: {
      ...IntergerStartingAtZero,
      min: 1,
      default: 1,
    },
    money: IntergerStartingAtZero,
    titles: {
      type: [{ type: String, ref: 'title' }],
    },
    activeTitle: {
      type: { type: String, ref: 'title' },
    },
    adventure: {
      rank: {
        type: String,
        enum: ['F', 'D', 'C', 'B', 'A', 'S', 'SS'],
        required: true,
        default: 'F',
      },
      currentQuest: {
        type: { type: String, ref: 'quest' },
      },
    },
    skill_mastery: {
      equipment: {
        blade_weapons: IntergerStartingAtZero,
        blunt_weapons: IntergerStartingAtZero,
        powerfists: IntergerStartingAtZero,
        unarmed: IntergerStartingAtZero,
        staffs: IntergerStartingAtZero,
        bows: IntergerStartingAtZero,
        shields: IntergerStartingAtZero,
        light_armor: IntergerStartingAtZero,
        medium_armor: IntergerStartingAtZero,
        heavy_armor: IntergerStartingAtZero,
      },
      magic: {
        fire: IntergerStartingAtZero,
        water: IntergerStartingAtZero,
        air: IntergerStartingAtZero,
        earth: IntergerStartingAtZero,
        light: IntergerStartingAtZero,
        dark: IntergerStartingAtZero,
        void: IntergerStartingAtZero,
        gravity: IntergerStartingAtZero,
        cosmic: IntergerStartingAtZero,
        time: IntergerStartingAtZero,
        electric: IntergerStartingAtZero,
        ice: IntergerStartingAtZero,
        crystal: IntergerStartingAtZero,
        toxic: IntergerStartingAtZero,
        illusion: IntergerStartingAtZero,
        summoning: IntergerStartingAtZero,
        blood: IntergerStartingAtZero,
        enhancement: IntergerStartingAtZero,
      },
      crafting: {
        smithing: IntergerStartingAtZero,
        spellcrafting: IntergerStartingAtZero,
        enchanting: IntergerStartingAtZero,
        tailoring: IntergerStartingAtZero,
        alchemy: IntergerStartingAtZero,
        cooking: IntergerStartingAtZero,
        metallurgy: IntergerStartingAtZero,
        medicine: IntergerStartingAtZero,
        engineering: IntergerStartingAtZero,
      },
      gathering: {
        mining: IntergerStartingAtZero,
        woodcutting: IntergerStartingAtZero,
        fishing: IntergerStartingAtZero,
        hunting: IntergerStartingAtZero,
        farming: IntergerStartingAtZero,
      },
      life: {
        athletics: IntergerStartingAtZero,
        speech: IntergerStartingAtZero,
        stealth: IntergerStartingAtZero,
        taming: IntergerStartingAtZero,
        archeology: IntergerStartingAtZero,
        awareness: IntergerStartingAtZero,
        swimming: IntergerStartingAtZero,
      },
      resistances: {
        fire: IntergerStartingAtZero,
        water: IntergerStartingAtZero,
        air: IntergerStartingAtZero,
        earth: IntergerStartingAtZero,
        light: IntergerStartingAtZero,
        dark: IntergerStartingAtZero,
        void: IntergerStartingAtZero,
        gravity: IntergerStartingAtZero,
        cosmic: IntergerStartingAtZero,
        time: IntergerStartingAtZero,
        electric: IntergerStartingAtZero,
        ice: IntergerStartingAtZero,
        crystal: IntergerStartingAtZero,
        toxic: IntergerStartingAtZero,
        illusion: IntergerStartingAtZero,
        blood: IntergerStartingAtZero,
      },
    },
    learned_character_skills: {
      type: [{ type: String, ref: 'skill' }],
    },
    learned_spells: {
      type: [{ type: String, ref: 'spell' }],
    },
    inventory: {
      head: {
        type: String,
        ref: 'itemstack',
      },
      chest: {
        type: String,
        ref: 'itemstack',
      },
      bottom: {
        type: String,
        ref: 'itemstack',
      },
      boots: {
        type: String,
        ref: 'itemstack',
      },
      gloves: {
        type: String,
        ref: 'itemstack',
      },
      weapon: {
        type: String,
        ref: 'itemstack',
      },
      offhand: {
        type: String,
        ref: 'itemstack',
      },
      bag: {
        type: [{ type: String, ref: 'itemstack' }],
      },
    },
  },
};
